/* Every photograph of every case study, with its size. The API sends the
   frames without their dimensions, and both the projects wall and the
   case-study strip need them to lay a frame out before it has loaded. */
export const FRAMES = [
  ['chath-restaurant', '/media/frames/chath-aerial.jpg', 1600, 792],
  ['chath-restaurant', '/media/frames/chath-facade.jpg', 1600, 900],
  ['chath-restaurant', '/media/frames/chath-entrance.jpg', 1600, 900],
  ['chath-restaurant', '/media/frames/chath-cabin.jpg', 1600, 900],
  ['chath-restaurant', '/media/frames/chath-indicator.jpg', 1600, 900],
  ['chath-restaurant', '/media/frames/chath-ceiling.jpg', 1600, 900],
  ['chath-restaurant', '/media/frames/chath-terrace.jpg', 1600, 900],
  ['chath-restaurant', '/media/frames/chath-inuse.jpg', 1600, 900],
  ['chilkuru-residence', '/media/frames/chilkuru-aerial.jpg', 1600, 2503],
  ['chilkuru-residence', '/media/frames/chilkuru-pavilion.jpg', 1600, 2844],
  ['chilkuru-residence', '/media/frames/chilkuru-entrance.jpg', 1600, 2844],
  ['chilkuru-residence', '/media/frames/chilkuru-corridor.jpg', 1600, 2844],
  ['chilkuru-residence', '/media/frames/chilkuru-capsule.jpg', 1600, 2503],
  ['chilkuru-residence', '/media/frames/chilkuru-atrium.jpg', 1600, 2844],
  ['chilkuru-residence', '/media/frames/chilkuru-ceiling.jpg', 1600, 2844],
  ['chilkuru-residence', '/media/frames/chilkuru-panel.jpg', 1600, 2844],
  ['chilkuru-residence', '/media/frames/chilkuru-lop.jpg', 1600, 2503],
  ['kashi-yadhav-residence', '/media/frames/kashi-exterior.jpg', 1600, 2560],
  ['kashi-yadhav-residence', '/media/frames/kashi-structure.jpg', 1600, 2844],
  ['kashi-yadhav-residence', '/media/frames/kashi-drive.jpg', 1600, 2844],
  ['kashi-yadhav-residence', '/media/frames/kashi-machine.jpg', 1600, 2844],
  ['kashi-yadhav-residence', '/media/frames/kashi-cabin.jpg', 1600, 2844],
  ['kashi-yadhav-residence', '/media/frames/kashi-interior.jpg', 1600, 2844],
  ['kashi-yadhav-residence', '/media/frames/kashi-lop.jpg', 1600, 2844],
  ['kashi-yadhav-residence', '/media/frames/kashi-floor.jpg', 1600, 2844],
  ['kashi-yadhav-residence', '/media/frames/kashi-shaft.jpg', 1600, 2844],
  ['kashi-yadhav-residence', '/media/frames/kashi-stair.jpg', 1600, 2844],
  ['lacheta-nivas', '/media/frames/lacheta-exterior.jpg', 1600, 2560],
  ['lacheta-nivas', '/media/frames/lacheta-lobby.jpg', 1600, 2844],
  ['lacheta-nivas', '/media/frames/lacheta-glass.jpg', 1600, 2844],
  ['lacheta-nivas', '/media/frames/lacheta-ceiling.jpg', 1600, 2844],
  ['lacheta-nivas', '/media/frames/lacheta-indicator.jpg', 1600, 2844],
  ['lacheta-nivas', '/media/frames/lacheta-cop.jpg', 1600, 2844],
  ['lacheta-nivas', '/media/frames/lacheta-inuse.jpg', 1600, 2844],
  ['lacheta-nivas', '/media/frames/lacheta-terrace.jpg', 1600, 2844],
  ['lekha-nilayam', '/media/frames/lekha-aerial.jpg', 1600, 900],
  ['lekha-nilayam', '/media/frames/lekha-approach.jpg', 1600, 900],
  ['lekha-nilayam', '/media/frames/lekha-hall.jpg', 1600, 900],
  ['lekha-nilayam', '/media/frames/lekha-cabin.jpg', 1600, 900],
  ['lekha-nilayam', '/media/frames/lekha-cop.jpg', 1600, 900],
  ['lekha-nilayam', '/media/frames/lekha-ceiling.jpg', 1600, 900],
  ['lekha-nilayam', '/media/frames/lekha-inuse.jpg', 1600, 900],
  ['lekha-nilayam', '/media/frames/lekha-corridor.jpg', 1600, 900],
  ['niloufer-cafe', '/media/frames/niloufer-cabin.jpg', 1600, 2844],
  ['niloufer-cafe', '/media/frames/niloufer-interior.jpg', 1600, 2844],
  ['niloufer-cafe', '/media/frames/niloufer-portrait.jpg', 1600, 2844],
  ['owaisi-hospitals', '/media/frames/owaisi-exterior.jpg', 1600, 2503],
  ['owaisi-hospitals', '/media/frames/owaisi-lobby.jpg', 1600, 2503],
  ['owaisi-hospitals', '/media/frames/owaisi-doors.jpg', 1600, 2503],
  ['owaisi-hospitals', '/media/frames/owaisi-cabin.jpg', 1600, 2503],
  ['owaisi-hospitals', '/media/frames/owaisi-cop.jpg', 1600, 2503],
  ['owaisi-hospitals', '/media/frames/owaisi-ceiling.jpg', 1600, 2503],
  ['owaisi-hospitals', '/media/frames/owaisi-waiting.jpg', 1600, 2503],
  ['owaisi-hospitals', '/media/frames/owaisi-corridor.jpg', 1600, 2503],
]


const SIZES = new Map(FRAMES.map(([, src, width, height]) => [src, { width, height }]))

/** the dimensions of a frame, or a 4:3 guess for one not listed */
export const sizeOf = (src) => SIZES.get(src) ?? { width: 1600, height: 1200 }
