# Generated by Django 5.2.17 on 2026-08-29 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Project categories',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=140)),
                ('client', models.CharField(blank=True, max_length=140)),
                ('location', models.CharField(default='Hyderabad, Telangana', max_length=140)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('statement', models.CharField(blank=True, help_text='One-line architecture statement under the hero.', max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('challenge', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('system', models.CharField(blank=True, max_length=90)),
                ('capacity', models.CharField(blank=True, max_length=60)),
                ('stops', models.CharField(blank=True, max_length=30)),
                ('door', models.CharField(blank=True, max_length=90)),
                ('drive', models.CharField(blank=True, max_length=90)),
                ('scope', models.CharField(blank=True, max_length=200)),
                ('hero_image_url', models.CharField(blank=True, max_length=300)),
                ('hero_video_url', models.CharField(blank=True, max_length=300)),
                ('loop_video_url', models.CharField(blank=True, max_length=300)),
                ('poster_url', models.CharField(blank=True, max_length=300)),
                ('is_portrait', models.BooleanField(default=False, help_text='Tick when the project film is shot vertically.')),
                ('is_featured', models.BooleanField(default=False)),
                ('lift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='catalog.lifttype')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('stage', models.CharField(choices=[('site', 'Site'), ('installation', 'Installation'), ('interior', 'Interior'), ('completion', 'Completion'), ('detail', 'Detail')], default='interior', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
