# Generated by Django 5.2.17 on 2026-08-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=140)),
                ('issuer', models.CharField(blank=True, max_length=140)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('certificate', models.FileField(blank=True, upload_to='certificates/')),
                ('certificate_url', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('head_office', 'Head office'), ('factory', 'Factory')], default='head_office', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(default='Hyderabad', max_length=80)),
                ('state', models.CharField(default='Telangana', max_length=80)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hours', models.CharField(blank=True, max_length=160)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('map_embed_url', models.URLField(blank=True, max_length=600)),
                ('directions_url', models.URLField(blank=True, max_length=600)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('drive', 'Drive'), ('motor', 'Motor'), ('controller', 'Controller'), ('door', 'Door'), ('safety', 'Safety'), ('cabin', 'Cabin')], default='drive', max_length=20)),
                ('component', models.CharField(blank=True, max_length=120)),
                ('logo', models.ImageField(blank=True, upload_to='partners/')),
                ('logo_url', models.CharField(blank=True, max_length=300)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Zion Lifts', max_length=120)),
                ('tagline', models.CharField(default='Engineered to rise.', max_length=200)),
                ('statement', models.TextField(default='Helping people move the right way — safer, quieter, better.', help_text='Used in the footer and as the closing line on About.')),
                ('phone', models.CharField(default='+91 91000 00000', max_length=40)),
                ('phone_service', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(default='info@zionlifts.com', max_length=254)),
                ('email_service', models.EmailField(blank=True, max_length=254)),
                ('founded_year', models.PositiveIntegerField(default=2012)),
                ('installations', models.PositiveIntegerField(default=1750)),
                ('team_size', models.CharField(default='95–100', max_length=20)),
                ('city', models.CharField(default='Hyderabad', max_length=80)),
                ('country', models.CharField(default='India', max_length=80)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('about', 'About'), ('projects', 'Projects'), ('home', 'Home')], default='about', max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('count_from', models.CharField(blank=True, help_text='Set to animate a count-up, e.g. 0', max_length=20)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
