# Generated by Django 5.2.17 on 2026-08-29 21:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('year', models.CharField(blank=True, max_length=12)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'FAQ category',
                'verbose_name_plural': 'FAQ categories',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name_plural': 'Journal categories',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=140)),
                ('intro', models.TextField(blank=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('year', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order', 'year'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='wrench', help_text='Key into the front-end icon set.', max_length=30)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('department', models.CharField(choices=[('leadership', 'Leadership'), ('engineering', 'Engineering'), ('manufacturing', 'Manufacturing'), ('installation', 'Installation & service'), ('design', 'Design')], default='engineering', max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('photo_url', models.CharField(blank=True, max_length=300)),
                ('is_leadership', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
                ('link_label', models.CharField(blank=True, help_text='e.g. "Explore Home Elevators"', max_length=120)),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('scope', models.CharField(default='general', help_text='general / contact — contact-scoped questions only show on /contact.', max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('institutional', 'Institutional'), ('interiors', 'Interiors'), ('installation', 'Installation'), ('factory', 'Factory'), ('awards', 'Awards'), ('people', 'People')], default='interiors', max_length=20)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('meta', models.CharField(blank=True, help_text='e.g. "Home Elevator - Private Residence - Hyderabad"', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='gallery/')),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('width', models.PositiveIntegerField(default=1600)),
                ('height', models.PositiveIntegerField(default=900)),
                ('is_featured', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True, help_text="Markdown-ish: '## ' starts a section, '> ' a pull quote, blank line splits paragraphs.")),
                ('hero_image_url', models.CharField(blank=True, max_length=300)),
                ('read_minutes', models.PositiveIntegerField(default=5)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.journalcategory')),
            ],
            options={
                'ordering': ['-published_at', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('heading', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='content.legaldocument')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('organisation', models.CharField(blank=True, max_length=140)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField()),
                ('video_url', models.CharField(blank=True, max_length=300)),
                ('poster_url', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
