"""What the site records about the people reading it.

Three tables, in the shape the questions are asked:

    Visitor -> Session -> PageView

A **Visitor** is one browser that has been here before, identified by a random
id that browser generated and keeps. A **Session** is one visit — a run of
activity that ends after ``ANALYTICS_SESSION_TIMEOUT_MINUTES`` of silence. A
**PageView** is one page opened during a visit.

The split is not normalisation for its own sake; it is what makes the dashboard
cheap. Device, browser, operating system, country and traffic source are
constant for the whole of a visit, so they are columns on ``Session`` and every
"how many visitors used mobile / came from Google / were in India" query reads
one row per visit rather than one per page. Only the page-level questions —
which paths, how long on each — touch the large table.

**On privacy.** There is no IP address column, no user-agent column and no user
foreign key here, and that is deliberate rather than incidental: an analytics
table is the one place in a codebase most likely to quietly become a log of who
read what. What is stored is the derived category ("Mobile", "Chrome", "India")
and never the raw value it came from. The visitor id is random and generated by
the browser; it identifies a browser across visits and nothing else about the
person holding it. See ``useragent.py`` and ``geo.py`` for where the narrowing
happens — it is on the way in, so the raw values are never written at all.

**Only real traffic is ever written here.** There is no seeder, no demo flag and
no fixture: every row in these tables was created by
``services.track`` answering a beacon from somebody's browser. That is a
property of the code rather than of a filter — there is no path that writes a
synthetic row, so there is nothing for a query to have to exclude, and a number
on the dashboard cannot be anything other than a count of real visits.

An empty table therefore means nobody has visited yet, and the dashboard says
exactly that rather than substituting a placeholder.
"""

from __future__ import annotations

import uuid

from django.conf import settings
from django.db import models
from django.utils import timezone


class Device(models.TextChoices):
    DESKTOP = "desktop", "Desktop"
    MOBILE = "mobile", "Mobile"
    TABLET = "tablet", "Tablet"
    BOT = "bot", "Bot"
    UNKNOWN = "unknown", "Unknown"


class Channel(models.TextChoices):
    """Where a visit came from, in the five buckets anyone actually acts on."""

    DIRECT = "direct", "Direct"
    SEARCH = "search", "Google / Search"
    SOCIAL = "social", "Social media"
    REFERRAL = "referral", "Referral"
    OTHER = "other", "Other"


class Visitor(models.Model):
    """One browser, across every visit it has made.

    ``key`` is the random id the browser generated and stores; it is the only
    thing tying two visits together and it means nothing outside this table. The
    integer primary key exists because ``PageView`` points at this row a great
    many times, and a 16-byte foreign key repeated across millions of rows is a
    measurably larger index than an 8-byte one.

    ``session_count`` and ``page_view_count`` are denormalised counters. They are
    not required — both are derivable — but "is this a first-time visitor?" is
    asked on the write path of every single page view, and answering it with a
    COUNT over the page-view table would make the tracker's cost grow with the
    visitor's history.
    """

    key = models.UUIDField(unique=True, editable=False)
    first_seen = models.DateTimeField(default=timezone.now, db_index=True)
    last_seen = models.DateTimeField(default=timezone.now, db_index=True)
    session_count = models.PositiveIntegerField(default=0)
    page_view_count = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [
            # "How many people first arrived in this window?" — the new-visitor
            # number on the traffic overview, and the only query that reads this
            # table by date rather than by key.
            models.Index(fields=["first_seen"], name="an_visitor_first_seen"),
        ]

    def __str__(self) -> str:
        return f"Visitor {self.key}"


class Session(models.Model):
    """One visit: a run of activity with no gap longer than the timeout.

    Every dimension the dashboard groups by is here rather than on the page
    view, because all of them are properties of the visit. The cost is one
    denormalised copy per visit; the saving is that a "devices" or "countries"
    query never touches the page-view table at all.

    ``ended_at`` is left null while a visit may still continue. Nothing closes
    it on a timer — a visit that stopped being touched is over by definition,
    and a background job whose only purpose is to write that fact down would be
    a moving part with no reader. Duration is ``last_activity_at - started_at``,
    which is what a session length actually is.
    """

    key = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE, related_name="sessions")

    started_at = models.DateTimeField(default=timezone.now)
    last_activity_at = models.DateTimeField(default=timezone.now)
    ended_at = models.DateTimeField(null=True, blank=True)
    page_view_count = models.PositiveIntegerField(default=0)

    # True when this was the visitor's very first visit. Stored rather than
    # derived: the alternative is comparing every session's start against its
    # visitor's first_seen at query time, on every returning-visitor panel.
    is_first = models.BooleanField(default=False)

    device = models.CharField(max_length=12, choices=Device.choices, default=Device.UNKNOWN)
    browser = models.CharField(max_length=32, default="Other")
    os = models.CharField(max_length=32, default="Other")

    channel = models.CharField(max_length=12, choices=Channel.choices, default=Channel.DIRECT)
    # Host only — "google.com", never the full referring URL. A search query
    # string or a path on someone's private wiki is not ours to keep.
    referrer_host = models.CharField(max_length=160, blank=True)

    country = models.CharField(max_length=64, blank=True)
    region = models.CharField(max_length=64, blank=True)
    city = models.CharField(max_length=64, blank=True)

    entry_path = models.CharField(max_length=300, blank=True)
    exit_path = models.CharField(max_length=300, blank=True)

    class Meta:
        ordering = ["-started_at"]
        indexes = [
            # Every dimension panel is "filter by window, group by column", so
            # what they all need is a cheap range scan on started_at.
            models.Index(fields=["started_at"], name="an_sess_started"),
            # The write path's first question: does this visitor have a live
            # session? Descending, because it wants the newest one.
            models.Index(fields=["visitor", "-last_activity_at"], name="an_sess_visitor_recent"),
            # "Online now" and the live feed, which read the tail of this column.
            models.Index(fields=["-last_activity_at"], name="an_sess_recent"),
        ]

    def __str__(self) -> str:
        return f"Session {self.key}"

    @property
    def duration_seconds(self) -> int:
        return int((self.last_activity_at - self.started_at).total_seconds())

    @property
    def is_bounce(self) -> bool:
        """A visit that saw one page and left.

        Counted on page views rather than on duration: a reader who spends four
        minutes on one article did not bounce in any sense worth reporting, and
        the industry's usual "single-page visit" definition is the one every
        other tool the client compares us against is using.
        """
        return self.page_view_count <= 1


class PageView(models.Model):
    """One page opened. The large table, and the only one that grows per action.

    ``visitor`` is denormalised alongside ``session`` so "unique visitors on
    /projects" is one index scan rather than a join back through sessions.

    ``event_key`` is the browser's idempotency token — one uuid minted per page
    view, resent unchanged if the request is retried. The unique constraint is
    what makes the tracking endpoint safe to call twice, which matters because
    ``sendBeacon`` gives no delivery signal and a flaky connection will retry.
    """

    event_key = models.UUIDField(unique=True, editable=False)
    visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE, related_name="page_views")
    session = models.ForeignKey(Session, on_delete=models.CASCADE, related_name="page_views")

    path = models.CharField(max_length=300)
    referrer_host = models.CharField(max_length=160, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    # Filled in when the *next* view in the same session arrives, so the last
    # page of every visit keeps a null here. That null is honest: nothing tells
    # us how long someone spent on the page they left from, and averaging a
    # zero into "time on page" would quietly drag every number down.
    duration_seconds = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            # The timeseries chart and the totals: a range scan, nothing else.
            models.Index(fields=["created_at"], name="an_pv_created"),
            # Top Pages, and one page's detail screen.
            models.Index(fields=["path", "created_at"], name="an_pv_path_created"),
            # Unique visitors within a window, without touching the session table.
            models.Index(fields=["visitor", "created_at"], name="an_pv_visitor_created"),
            # Closing out the previous view's duration when the next one lands.
            models.Index(fields=["session", "-created_at"], name="an_pv_session_recent"),
        ]

    def __str__(self) -> str:
        return f"{self.path} @ {self.created_at:%Y-%m-%d %H:%M}"


def session_timeout_minutes() -> int:
    """How long a visit survives silence before the next view starts a new one."""
    return int(getattr(settings, "ANALYTICS_SESSION_TIMEOUT_MINUTES", 30))


def online_window_minutes() -> int:
    """How recently a visit must have been touched to count as "online now"."""
    return int(getattr(settings, "ANALYTICS_ONLINE_WINDOW_MINUTES", 5))
