# Generated by Django 5.2.17 on 2026-08-31 12:37

import apps.knowledge.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive knowledge bases keep their documents but are not searched.')),
            ],
            options={
                'verbose_name': 'Knowledge base',
                'verbose_name_plural': 'Knowledge bases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='What staff call this document.', max_length=200)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracting', 'Extracting text'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='uploaded', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(max_length=400, upload_to=apps.knowledge.models.document_upload_path)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracting', 'Extracting text'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='uploaded', max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_count', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=200)),
                ('embedding_model_version', models.CharField(blank=True, max_length=40)),
                ('embedding_dimension', models.PositiveIntegerField(blank=True, null=True)),
                ('collection', models.CharField(blank=True, help_text="Vector collection holding this version's chunks.", max_length=200)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.document')),
            ],
            options={
                'ordering': ['document', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='active_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for', to='knowledge.documentversion'),
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('ingest', 'Ingest'), ('reindex', 'Reindex'), ('delete', 'Delete')], default='ingest', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Whole percent, 0-100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_stage', models.CharField(blank=True, choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracting', 'Extracting text'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], help_text='The lifecycle stage the worker last reported.', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=155)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='knowledge.document')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='knowledge.documentversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgebase'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-version_number'], name='knowledge_d_documen_3ebf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['status'], name='knowledge_d_status_06d84f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['content_hash'], name='knowledge_d_content_213415_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_document_version_number'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['document', '-created_at'], name='knowledge_i_documen_a8c415_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['status', '-created_at'], name='knowledge_i_status_7e4df1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['knowledge_base', '-created_at'], name='knowledge_d_knowled_f63e06_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='knowledge_d_status_79949e_idx'),
        ),
    ]
