# Generated by Django 5.2.17 on 2026-08-29 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('group', models.CharField(default='residential', help_text='residential / commercial / institutional / industrial', max_length=40)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('image_url', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('index', models.CharField(default='01', max_length=4)),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField(blank=True)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=90)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('test_procedure', models.TextField(blank=True, help_text='What the safety-lab section describes for this test.')),
                ('standard', models.CharField(blank=True, max_length=120)),
                ('media_url', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinishOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('material', 'Wall material'), ('floor', 'Flooring'), ('light', 'Lighting'), ('door', 'Door'), ('control', 'Control panel'), ('handrail', 'Handrail')], db_index=True, max_length=20)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('swatch_hex', models.CharField(default='#C9B79A', max_length=9)),
                ('swatch_hex_2', models.CharField(blank=True, help_text='Second stop for a two-tone swatch.', max_length=9)),
                ('texture', models.ImageField(blank=True, upload_to='finishes/')),
                ('texture_url', models.CharField(blank=True, max_length=300)),
                ('tier', models.CharField(default='standard', max_length=20)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='LiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=90)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('eyebrow', models.CharField(blank=True, max_length=60)),
                ('tagline', models.CharField(max_length=180)),
                ('summary', models.TextField(help_text='One paragraph — used on cards and the index grid.')),
                ('overview', models.TextField(blank=True, help_text='Two paragraphs for the product page.')),
                ('speed', models.CharField(blank=True, max_length=40)),
                ('capacity', models.CharField(blank=True, max_length=60)),
                ('stops', models.CharField(blank=True, max_length=40)),
                ('drive', models.CharField(blank=True, max_length=80)),
                ('min_floors', models.PositiveIntegerField(default=2)),
                ('max_floors', models.PositiveIntegerField(default=12)),
                ('min_persons', models.PositiveIntegerField(default=3)),
                ('max_persons', models.PositiveIntegerField(default=13)),
                ('pit_depth', models.CharField(blank=True, max_length=40)),
                ('headroom', models.CharField(blank=True, max_length=40)),
                ('shaft_footprint', models.CharField(blank=True, max_length=60)),
                ('machine_room', models.CharField(blank=True, default='Not required', max_length=40)),
                ('hero_image_url', models.CharField(blank=True, max_length=300)),
                ('hero_video_url', models.CharField(blank=True, max_length=300)),
                ('accent', models.CharField(default='#048D8E', max_length=9)),
                ('is_featured', models.BooleanField(default=False)),
                ('applications', models.ManyToManyField(blank=True, related_name='lift_types', to='catalog.application')),
                ('safety_features', models.ManyToManyField(blank=True, related_name='lift_types', to='catalog.safetyfeature')),
            ],
            options={
                'verbose_name': 'Lift type',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiftSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('group', models.CharField(default='Dimensions', max_length=60)),
                ('label', models.CharField(max_length=90)),
                ('value', models.CharField(max_length=140)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('lift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.lifttype')),
            ],
            options={
                'ordering': ['group', 'order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('hero', 'Hero'), ('gallery', 'Gallery'), ('cabin', 'Cabin'), ('detail', 'Detail'), ('diagram', 'Diagram')], default='gallery', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='lifts/')),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('lift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.lifttype')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiftVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('capacity', models.CharField(blank=True, max_length=60)),
                ('persons', models.CharField(blank=True, max_length=30)),
                ('speed', models.CharField(blank=True, max_length=40)),
                ('shaft', models.CharField(blank=True, max_length=60)),
                ('lift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.lifttype')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
