# Generated by Django 5.2.17 on 2026-08-29 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('maintenance', 'Maintenance / AMC'), ('breakdown', 'Breakdown support'), ('modernisation', 'Modernisation'), ('spares', 'Spare parts')], default='maintenance', max_length=20)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('soon', 'Within a few days'), ('urgent', 'Urgent - lift is down')], default='routine', max_length=20)),
                ('name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_name', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('lift_reference', models.CharField(blank=True, max_length=90)),
                ('message', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('scheduled', 'Scheduled'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_type', models.CharField(blank=True, choices=[('villa', 'Villa / independent house'), ('apartment', 'Apartment building'), ('office', 'Office / commercial'), ('hotel', 'Hotel / hospitality'), ('hospital', 'Hospital / healthcare'), ('institutional', 'Institutional / government'), ('industrial', 'Industrial / warehouse'), ('retail', 'Retail'), ('other', 'Other')], max_length=30)),
                ('project_stage', models.CharField(blank=True, choices=[('planning', 'Planning / design'), ('construction', 'Under construction'), ('ready', 'Building ready'), ('replacement', 'Replacing an existing lift')], max_length=30)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('floors', models.CharField(blank=True, max_length=30)),
                ('lift_type_note', models.CharField(blank=True, help_text='Set to "not-sure" when no type was chosen.', max_length=60)),
                ('capacity', models.CharField(blank=True, max_length=60)),
                ('stops', models.CharField(blank=True, max_length=30)),
                ('installation_kind', models.CharField(blank=True, max_length=30)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Cabin configurator selections carried over from the product page.')),
                ('name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('source_path', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost'), ('spam', 'Spam')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('lift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='catalog.lifttype')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='enquiries/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='enquiries.enquiry')),
            ],
        ),
    ]
